{% set name = "schwifty" %}
{% set version = "2022.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schwifty-{{ version }}.tar.gz
  sha256: 4c9e7853ca0c413623af9a8549b0e1125b876283c37950d63d9a2cd15c610521

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - importlib_metadata
    - importlib_resources
    - iso3166
    - pycountry
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - schwifty
    - schwifty.checksum
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: http://github.com/mdomke/schwifty
  summary: Validate/generate IBANs and BICs
  doc_url: https://pythonhosted.org/schwifty/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
