{% set name = "schwifty" %}
{% set version = "2022.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schwifty-{{ version }}.tar.gz
  sha256: ff3c4ad2951f8391b9c3d13e401b751f5d8b77981673e59a91074d5513121620

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=45
    - setuptools_scm >=6.0
  run:
    - importlib_metadata
    - importlib_resources
    - iso3166
    - pycountry
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - schwifty
    - schwifty.checksum
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: http://github.com/mdomke/schwifty
  summary: Validate/generate IBANs and BICs
  doc_url: https://pythonhosted.org/schwifty/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
